### ISSUE TITLE
最新のmasterで`bad argument`と言われる

### ISSUE THREAD

**Issue by marmot1123** [wtsnjp/llmk#1]
最新のmaster (`94bb391`)でllmkを走らせると，

```
/usr/local/bin/llmk:490: bad argument #1 to 'pairs' (table expected, got string)
```

というエラーを吐いて動いてくれませんでした．
どのコミットから失敗するのか二分探索したところ，
`4bd1b9a` までは成功し， `6e2c5ac` から失敗しているようです．
Luaが分からず，`git diff` してみてもいまいち分からなかったのですが，
報告させてもらいます．

実行したLaTeXファイルのllmk用コードは以下の通りです．
（もう古い書き方なのかもしれませんが）

```
%+++
% sequence = ["latex", "latex", "latex", "dvipdf"]
%
% [programs.latex]
%   command = "platex"
%   opts = "-halt-on-error"
%   args = "%T"
%
% [programs.dvipdf]
%   command = "dvipdfmx"
%   args = "%B.dvi"
%
%+++
```

最初のissueでルールが分からず，横着して日本語で書いてしまいましたが，
英語の方が良かったでしょうか？そちらの方が良ければ後で時間があるときに英訳します．

**Comment by marmot1123** [comment]
配列にしたところ，無事最新のmasterでビルドが通りました．
迅速な対応ありがとうございます．
これからも自分の分かる範囲で何か見つけ次第報告させてもらいます．

**Comment by wtsnjp** [comment]
大変遅くなりましたが，先ほどコミット d5c52d071c3f979fab8cc7a6eed35ec187124307 で予告していた「型検査」の機能を導入しました．その副産物として，元々 @marmot1123 さんが書かれていたように `opts` や `args` に（配列ではなく）文字列を与えた場合にも適切な読み替えがなされるようになったはずです．
