### ISSUE TITLE
Support for !TeX program

### ISSUE THREAD

**Issue by koppor** [wtsnjp/llmk#12]
According to https://tex.stackexchange.com/a/78352/9075, `!TeX program` is also understood by TeXShop. I have it in use in many documents, e.g., in my template for scientific theses (https://github.com/latextemplates/scientific-thesis-template/blob/main/main-english.tex).

Would it be possible to add support for `!TeX program` in addition to `!TeX TS-program`?

```latex
% !TeX spellcheck = de-DE
% !TeX encoding = utf8
% !TeX program = pdflatex
% !BIB program = bibtex
% -*- coding:utf-8 mod:LaTeX -*-
```

**Comment by wtsnjp** [comment]
The syntax of `!TEX program` is already supported (cf. Section 4.1 of the reference manual.)

![Screen Shot 2021-08-18 at 17 20 49](https://user-images.githubusercontent.com/9448125/129863986-0b204853-f7cf-43fb-b1df-6ca2202381eb.png)

But, I didn't know `TeX` can be not entirely capitalized. Does TeXShop recognize the directive case-intensively?

**Comment by koppor** [comment]
Thank you - I think, I mixed up some files when experimenting with llmk.

**Comment by koppor** [comment]
I closed too early, sorry. I was fully aware that `!TEX` is supported. I requested support for `!TeX`.

> But, I didn't know `TeX` can be not entirely capitalized. 

I am using TeXStudio - and it says `!TeX`:

![grafik](https://user-images.githubusercontent.com/1366654/130366099-9f60ae1c-c87d-4beb-a076-a9ced93cbb24.png)

Source: http://transit.iut2.upmf-grenoble.fr/doc/texstudio/html/usermanual_en.html#TEXCOM

> Does TeXShop recognize the directive case-insensitively?

I do not own a Mac, so I cannot test. My first aim is to support [TeXStudio](https://tex.stackexchange.com/a/5281) 😇 .

**Comment by wtsnjp** [comment]
I've just made a change to allow `%!TeX program` to support the magic comment mentioned in the TeXStudio document.

**Comment by koppor** [comment]
Thank you! Can't wait for a new release!
