### ISSUE TITLE
default command "clean" like "latexmk (-c |-C)"

### ISSUE THREAD

**Issue by hidaruma** [wtsnjp/llmk#4]
latexmk has options `-c` and `-C` to remove temporary files like ".aux" generated with `latex` and other tools' command. Now, llmk can set custom command to remove these. But I think llmk should to be able to use it initially because it is used fequently.

**Comment by hidaruma** [comment]
@wtsnjp I think that the local functions -- `check_filename` and `replace_specifier` -- are useful to implement `-c` | `-C` cmds. Do you have any reasons that they can't use like `llmk.util.check_filename(fn)` in llmk.lua?

**Comment by wtsnjp** [comment]
That is just simply because *at this point* those are used only in the "runner" module. If you think those functions are useful for the module you're implementing (maybe "cleaner"?), you may move those to the "util" module 👍
