### ISSUE TITLE
dvips の後に dvipdf が実行されてしまう

### ISSUE THREAD

**Issue by doraTeX** [wtsnjp/llmk#6]
`examples` ディレクトリの `dvips.tex` について，

```
$ texlua llmk.lua dvips.tex
```

を実行してみると，`platex` → `dvips` → `ps2pdf` の後にさらに `dvipdfmx` の起動がなされているようで，最終的に仕上がった PDF は dvipdfmx 製ということになっている模様です。

**Comment by wtsnjp** [comment]
ありがとうございます．バグですね．かなり根本的なやつでした．上記コミットで修正されたはずです．

**Comment by doraTeX** [comment]
確認できました。ありがとうございます！
