### ISSUE TITLE
Confusing terminology for program names

### ISSUE THREAD

**Issue by LambdaP** [wtsnjp/llmk#8]
Hello,

I’m pretty excited about `llmk`, which looks really promising. Thanks for setting that up!

I think the language in the documentation is more confusing that it needs to be when it comes to program names. When reading…

```
\begin{confkey}{bibtex}{type: \type{string}}[default: \code{"bibtex"}]
The command to use for the \progname{bibtex} program. Internally, this key is
an alias for the \ckey{command} key in the \progname{bibtex} entry. If the
\ckey{command} key is specified in the \ckey{programs} table, this alias is
ineffective.
\end{confkey}
```

…it’s really not clear at first that this key can be used to select `biber` as the reference management engine. Looking further down…

```
\Program{bibtex} The entry for the {\BibTeX} program and friends. The
\progname{latex} program is set as \ckey{postprocess} so that to make sure
rerunning {\LaTeX} command after this execution.
%
\begin{lstlisting}[style=toml]
[programs.bibtex]
command = "bibtex"
target = "%B.bib"
args = ["%B"]
postprocess = "latex"
\end{lstlisting}
```

…there's this mysterious expression "and friends", but its meaning is not particularly transparent.
In fact, the only passage where the fact that `biber` can be used there is apparent is talking about something else entirely (TeXShop directives):

```
The \meta{command} part will be passed to the \ckey{bibtex} key of \prog{llmk}.
For both of the two directives, only the topmost ones are effective; the others
will be ignored. For example, the following two configuration are equivalent:\\
%
\begin{minipage}[t]{.5\textwidth}
\begin{lstlisting}[style=latex]
% !TEX TS-program = xelatex
% !BIB TS-program = biber
\documentclass{article}
\end{lstlisting}
\end{minipage}
\begin{minipage}[t]{.49\textwidth}
\begin{lstlisting}[style=latex]
% +++
% latex = "xelatex"
% bibtex = "biber"
% +++
\documentclass{article}
\end{lstlisting}
\end{minipage}
```

I think there are two ways to approach this, one light and one which sort of break things.

## The light way: elaborate in the documentation

Things would be much better if the `bibtex` key came with examples. The above passages could be augmented in the following manner:

```
\begin{confkey}{bibtex}{type: \type{string}}[default: \code{"bibtex"}]
The command to use for the \progname{bibtex}-like program, such as 
\code{"bibtex"} or \code{"biber"}. Internally, this key is
an alias for the \ckey{command} key in the \progname{bibtex} entry. If the
\ckey{command} key is specified in the \ckey{programs} table, this alias is
ineffective.
\end{confkey}
```

```
\Program{bibtex} The entry for the {\BibTeX} program and friends like 
\code{"biber"}. The
\progname{latex} program is set as \ckey{postprocess} so that to make sure
rerunning {\LaTeX} command after this execution.
%
\begin{lstlisting}[style=toml]
[programs.bibtex]
command = "bibtex"
target = "%B.bib"
args = ["%B"]
postprocess = "latex"
\end{lstlisting}
```

I have not read the documentation in depth, but I suspect the `latex` key would benefit from the same treatment, although it is easier to understand what it does due to using `lualatex` as the default value.

## The bulldozer way: re-think keys and programs

What I think the above points at is that `bibtex` doesn't describe what the key does very well, since its real meaning is something like "the program you use to produce a `.bbl` file". I’m not really sure what this says, or if there’s an obviously best response to this problem.

If starting from scratch was an option, I’d probably try to argue that a name like `bibengine` is more descriptive and does not bind the key to a specific technology – and that similarly we could use `latexengine` and `indexengine` in place of `latex` and `makeindex`. Maybe a system of alias keys could be used to achieve the same thing, but I’m not really sure how much it would be worth the trouble or if the format allows for that sort of thing.

Anyhow, this is really me throwing out my raw feelings and should not be taken too strongly. This is a really nice project.

**Comment by wtsnjp** [comment]
Hello, thanks for having an interest in llmk, and opening this issue!

> I think there are two ways to approach this, one light and one which sort of break things.

Ok, I take the light approach for now and [already done](https://github.com/wtsnjp/llmk/commit/10ae3416214dcfaa3e51c247b2f5a17de13264f3). Thanks for your suggestion.

> What I think the above points at is that bibtex doesn't describe what the key does very well

Actually, the `bibtex` (resp. `latex` and `makeindex`) key is an alias for the `command` key in the `[programs.bibtex]` (resp. `[programs.latex]` and `[programs.makeindex]`) table. Thus, the current key names are simple and clear from my point of view.

The default settings in the `[programs.bibtex]` are designed to work nicely with BibTeX in the first place; it should work fine as well for the reference management tools that are designed to be compatible with BibTeX, but not for the other tools, even if they can be used as reference management systems, that are not compatible enough to BibTeX. In other words, the key is not for *all* reference management systems; if you want to use an arbitrary system, in general, you should make another entry in the `programs` table independent of the `[programs.bibtex]` entry.

But ok, that change can be implemented not necessary as breaking one. In case many users also think the top-level keys, i.e., `bibtex`, `latex`, `makeindex`, and so on, are confusing, I can add aliases with more general names, say `bibengine` and similar as you suggested, at some point in the future. For now, let us see how other users will think about it.

**Comment by LambdaP** [comment]
> Ok, I take the light approach for now and [already done](https://github.com/wtsnjp/llmk/commit/10ae3416214dcfaa3e51c247b2f5a17de13264f3). Thanks for your suggestion.

Hey, thanks!

> 
> > What I think the above points at is that bibtex doesn't describe what the key does very well
> 
> Actually, the `bibtex` (resp. `latex` and `makeindex`) key is an alias for the `command` key in the `[programs.bibtex]` (resp. `[programs.latex]` and `[programs.makeindex]`) table. Thus, the current key names are simple and clear from my point of view.

Sure. The key is named after the corresponding `programs` entry, and it would probably be wrong to do otherwise. I think that wasn’t so clear to me when I started writing my issue.

> In other words, the key is not for _all_ reference management systems; if you want to use an arbitrary system, in general, you should make another entry in the `programs` table independent of the `[programs.bibtex]` entry.

OK cool, and I think the change in the documentation reflects this stance well.

> But ok, that change can be implemented not necessary as breaking one. In case many users also think the top-level keys, i.e., bibtex, latex, makeindex, and so on, are confusing, I can add aliases with more general names, say bibengine and similar as you suggested, at some point in the future. For now, let us see how other users will think about it.

It might very well not be necessary: `latexmk` has survived for many moons calling its engine option `$pdflatex` and people don't seem to be complaining.

Thanks for reacting so fast.
